### ISSUE TITLE
Refactor out schematics Python dependency, prior to backend upgrade to Python 3.11

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/tasking-manager#5725]
`schematics` is unmaintained (last commit 2021) and breaks when used with Python 3.10.

Example traceback:
```
  File "/usr/src/app/manage.py", line 11, in <module>
    from backend.services.users.authentication_service import AuthenticationService
  File "/usr/src/app/backend/services/users/authentication_service.py", line 9, in <module>
    from backend.services.messaging.message_service import MessageService
  File "/usr/src/app/backend/services/messaging/message_service.py", line 12, in <module>
    from backend.models.dtos.message_dto import MessageDTO, MessagesDTO
  File "/usr/src/app/backend/models/dtos/message_dto.py", line 1, in <module>
    from schematics import Model
  File "/home/appuser/.local/lib/python3.10/site-packages/schematics/__init__.py", line 6, in <module>
    from . import deprecated
  File "/home/appuser/.local/lib/python3.10/site-packages/schematics/deprecated.py", line 8, in <module>
    from .types.serializable import Serializable
  File "/home/appuser/.local/lib/python3.10/site-packages/schematics/types/__init__.py", line 2, in <module>
    from .base import *
  File "/home/appuser/.local/lib/python3.10/site-packages/schematics/types/base.py", line 19, in <module>
    from collections import Iterable, OrderedDict
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

Usage of the package should be refactored out, in favour of another modelling package.
Looks like it's referenced quite a lot, so it's a sizeable refactor of the codebase.

**Comment by eternaltyro** [comment]
Seems like the library has been abandoned: https://github.com/schematics/schematics/issues/628

**Comment by spwoodcock** [comment]
I would recommend Pydantic (the package that FastAPI uses underneath). It's great!

**Comment by spwoodcock** [comment]
Sorry to raise the alarm, but if we increment `schematics` one minor version 2.1.0 --> 2.1.1, then it may work with Python 3.10 (unusual for a patch in semver 🧐).
See #5642.
We may be able to move ahead with the Python 3.10 upgrade before this task is done (I will update the title).

This update is essential going forward though, as the last real development to `schematics` was in 2018. Especially if we want to use Python 3.11 (schematics breaks completely).

**Comment by eternaltyro** [comment]
This change is currently in staging environment.
